volumes:
  db:
    driver: local

services:
  db:
    image: postgres:17.0
    restart: always
    ports:
      - '5432:13789'
    volumes:
      - db:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: workshop
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -d postgres"  ]
      interval: 10s
      timeout: 3s
      retries: 3
  api:
    build:
      context: ./
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://db:5432/workshop
      - SPRING_DATASOURCE_USERNAME=luiz
      - SPRING_DATASOURCE_PASSWORD=123456
    depends_on:
      - db
    ports:
      - '9091:9091'
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:9091"]
      interval: 5s
      retries: 5
      start_period: 3s