volumes:
  db:
    driver: local

services:
  db:
    image: postgres:17.0
    restart: always
    ports:
      - '5432:13789'
    volumes:
      - db:/var/lib/postgresql/data
      - ./initdb:/docker-entrypoint-initdb.d/create_database.sql
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: workshop
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U postgres"  ]
      interval: 10s
      timeout: 3s
      retries: 3
  api:
    build:
      context: ./
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://db:5432/workshop
      - SPRING_DATASOURCE_USERNAME=postgres
      - SPRING_DATASOURCE_PASSWORD=postgres
    depends_on:
      - db
    ports:
      - '9091:9091'