spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/workshop
    username: luiz
    password: luiz
    driver-class-name: org.postgresql.Driver
  flyway:
    locations: classpath:db/migration
    default-schema: public
    baseline-on-migrate: true

logging:
  level:
    org:
      springframework:
        security: TRACE
      hibernate:
        SQL: DEBUG
        type:
          descriptor:
            sql:
              BasicBinder: TRACE
      flywaydb: DEBUG