spring:
  messages:
    encoding: UTF-8
    basename: messages
  datasource:
    url: jdbc:postgresql://localhost:5432/workshop
    username: luiz
    password: luiz
    driver-class-name: org.postgresql.Driver
  flyway:
    locations: classpath:db/migration
    default-schema: public
    baseline-on-migrate: true
stripe:
  api:
    key: sk_test_51Q7k32RusRKcok4WL9VIT5BBMbZZCSoCAzjPcLopJ4OslV8jqTp6kzqFJ6Z3qlaTBjDH78Wj1VCDIH5tXyBYyszn00yTAWN149
    secret: whsec_k2yL5437EPhC8Vu9Y8UV51dQyqU1lAga

logging:
  level:
    org:
      springframework:
        security: TRACE
      hibernate:
        SQL: DEBUG
        type:
          descriptor:
            sql:
              BasicBinder: TRACE
      flywaydb: DEBUG